### ISSUE TITLE
How

### ISSUE THREAD

**Issue by SansHelvetica** [HaoJun0823/CODEVEIN-Stat-Changer#1]
How does this even work? You have an application called "CodeVein Stat Changer" but it doesnt really DO anything, just opens the file and says "success!"

But when I look at the guide, its says i need hex editor? so what is the StatChanger for? 

also, the hex editor isnt taking the uasset properly.

please explain your guide in better detail it isnt easy to understand.

**Comment by HaoJun0823** [comment]
This works.
However you can now use something more functional:
https://github.com/kaiheilos/Utilities
This tool is even more powerful.

PS: I do not provide CODE VEIN mod making tutorials, if you want to modify uasset content, you need to learn from the community.

**Comment by HaoJun0823** [comment]
This tool is actually a convenient version of pointing to the wiki, allowing users to operate without hex editing.

**Comment by SansHelvetica** [comment]
also how do you know which file is meant for which item? idk what Jinkaku is for example.

**Comment by HaoJun0823** [comment]
good question.

I can only be sure by recording the information in the game against the information in the file.

And this is what most modders do in most games.

Maybe you can ask others if they have specific records, because the naming rules of official developers are extremely confusing (more prominent in their skill design).
